apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  workspaces: #<1>
  - name: shared-workspace
  params:
#...
  tasks: #<2>
  - name: build-image
    taskRef:
      resolver: cluster
      params:
      - name: kind
        value: task
      - name: name
        value: buildah
      - name: namespace
        value: openshift-pipelines
    workspaces: #<3>
    - name: source #<4>
      workspace: shared-workspace #<5>
    params:
    - name: TLSVERIFY
      value: "false"
    - name: IMAGE
      value: $(params.IMAGE)
    runAfter:
    - fetch-repository
  - name: apply-manifests
    taskRef:
      name: apply-manifests
    workspaces: #<6>
    - name: source
      workspace: shared-workspace
    runAfter:
      - build-image
#...
