apiVersion: triggers.tekton.dev/v1beta1 #<1>
kind: Trigger #<2>
metadata:
  name: vote-trigger #<3>
spec:
  taskRunTemplate:
    serviceAccountName: pipeline #<4>
  interceptors:
    - ref:
        name: "github" #<5>
      params: #<6>
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: vote-app #<7>
  template: #<8>
     ref: vote-app
---
apiVersion: v1
kind: Secret #<9>
metadata:
  name: github-secret
type: Opaque
stringData:
  secretToken: "1234567"
