apiVersion: triggers.tekton.dev/v1beta1 #<1>
kind: TriggerTemplate #<2>
metadata:
  name: vote-app #<3>
spec:
  params: #<4>
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
    default: {pipelines-ver}
  - name: git-repo-name
    description: The name of the deployment to be created / patched

  resourcetemplates: #<5>
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      name: build-deploy-$(tt.params.git-repo-name)-$(uid)
    spec:
      taskRunTemplate:
        serviceAccountName: pipeline
      pipelineRef:
        name: build-and-deploy
      params:
      - name: deployment-name
        value: $(tt.params.git-repo-name)
      - name: git-url
        value: $(tt.params.git-repo-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/$(tt.params.git-repo-name)
      workspaces:
      - name: shared-workspace
        volumeClaimTemplate:
         spec:
          accessModes:
           - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
