apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipeline-pr-main
annotations:
  pipelinesascode.tekton.dev/on-target-branch: "[main]" #<1>
  pipelinesascode.tekton.dev/on-event: "[pull_request]"
# ...
