apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators
spec:
  channel:  <channel name> #<1>
  name: openshift-pipelines-operator-rh #<2>
  source: redhat-operators #<3>
  sourceNamespace: openshift-marketplace #<4>
