apiVersion: tekton.dev/v1
kind: Task
metadata:
  generateName: something-
spec:
  params:
  - name: myWorkspaceSecret
  steps:
  - image: registry.redhat.io/ubi/ubi8-minimal:latest
    script: |
      echo “Hello World”
  workspaces:
  - name: myworkspace
    secret:
      secretName: $(params.myWorkspaceSecret)
